https://github.com/MauricioGomez-2520612022/etl-data-pipeline-2520612022-

In [54]:
import pandas as pd

In [55]:
url = "https://raw.githubusercontent.com/MauricioGomez-2520612022/etl-data-pipeline-2520612022-/refs/heads/main/data/RAW/F_pedidos.csv"

In [56]:
f_pedidos_df = pd.read_csv(url)

f_pedidos_df.head()

  id_pedido id_cliente fecha_pedido    monto     estado
0   PED7000     CL1138   2024-11-28  1984.03   enviado
1   PED7001        NaN   2025-01-31  2395.24  cancelado
2   PED7002     CL1067   2024-07-13   433.46  cancelado
3   PED7003     CL1097   2025-05-02   352.01  cancelado
4   PED7004     CL1068   2024-12-20  1182.84    enviado

In [57]:
# Limpiar y normalizar los nombres de las columnas
f_pedidos_df.columns = f_pedidos_df.columns.str.strip().str.lower()

In [58]:
# Convertir la columna 'fecha_pedido' a formato datetime
f_pedidos_df['fecha_pedido'] = pd.to_datetime(f_pedidos_df['fecha_pedido'], errors='coerce')

In [59]:
import re

# Eliminar el símbolo '$', 'USD', espacios y cualquier texto no numérico, luego convertir a tipo numérico
f_pedidos_df['monto'] = f_pedidos_df['monto'].apply(lambda x: re.sub(r'[\$USD\ :]', '', str(x)))

# Convertir la columna 'monto' a tipo numérico
f_pedidos_df['monto'] = pd.to_numeric(f_pedidos_df['monto'], errors='coerce')

In [60]:
# Convertir la columna 'estado' a un formato consistente (capitalizar correctamente)
f_pedidos_df['estado'] = f_pedidos_df['estado'].str.title()

In [61]:
# Rellenar valores nulos en 'id_cliente' con NaN
f_pedidos_df['id_cliente'] = f_pedidos_df['id_cliente'].replace([None, ''], pd.NA)

In [62]:
# Verificar los primeros registros después de las transformaciones
f_pedidos_df.head()

  id_pedido id_cliente fecha_pedido    monto     estado
0   PED7000     CL1138   2024-11-28  1984.03   Enviado
1   PED7001       <NA>   2025-01-31  2395.24  Cancelado
2   PED7002     CL1067   2024-07-13   433.46  Cancelado
3   PED7003     CL1097   2025-05-02   352.01  Cancelado
4   PED7004     CL1068   2024-12-20  1182.84    Enviado

In [63]:

# Separar los datos válidos (id_pedido, id_cliente y monto no nulos)
validos_df = f_pedidos_df[
    f_pedidos_df['id_pedido'].notna() &
    f_pedidos_df['id_cliente'].notna() &
    f_pedidos_df['monto'].notna()
].copy()

# Separar los datos rechazados (id_pedido, id_cliente o monto nulos)
rechazados_df = f_pedidos_df[
    f_pedidos_df['id_pedido'].isna() |
    f_pedidos_df['id_cliente'].isna() |
    f_pedidos_df['monto'].isna()
].copy()

# Ver los registros válidos y rechazados
print(validos_df.head())
print(rechazados_df.head())

  id_pedido id_cliente fecha_pedido    monto       estado
0   PED7000     CL1138   2024-11-28  1984.03     Enviado
2   PED7002     CL1067   2024-07-13   433.46    Cancelado
3   PED7003     CL1097   2025-05-02   352.01    Cancelado
4   PED7004     CL1068   2024-12-20  1182.84      Enviado
5   PED7005     CL1030   2024-04-02  2154.60  Preparacion
   id_pedido id_cliente fecha_pedido    monto       estado
1    PED7001       <NA>   2025-01-31  2395.24    Cancelado
25   PED7025     CL1007   2024-08-22      NaN  Preparacion
56   PED7056       <NA>   2024-09-16   592.51      Enviado
63   PED7063     CL1096   2024-03-25      NaN    Entregado
74   PED7074       <NA>   2024-08-04   723.41    Pendiente

In [64]:
# Definir la función para determinar el motivo de rechazo
def motivo(row):
    motivos = []

    if pd.isna(row['id_pedido']):
        motivos.append("id_pedido_vacio")

    if pd.isna(row['id_cliente']):
        motivos.append("id_cliente_vacio")

    if pd.isna(row['monto']):
        motivos.append("monto_vacio")

    return ",".join(motivos)

# Motivo_rechazo
rechazados_df["motivo_rechazo"] = rechazados_df.apply(motivo, axis=1)

# Verificar los registros rechazados con la nueva columna
rechazados_df.head()

   id_pedido id_cliente fecha_pedido    monto       estado    motivo_rechazo
1    PED7001       <NA>   2025-01-31  2395.24    Cancelado  id_cliente_vacio
25   PED7025     CL1007   2024-08-22      NaN  Preparacion       monto_vacio
56   PED7056       <NA>   2024-09-16   592.51      Enviado  id_cliente_vacio
63   PED7063     CL1096   2024-03-25      NaN    Entregado       monto_vacio
74   PED7074       <NA>   2024-08-04   723.41    Pendiente  id_cliente_vacio

In [65]:
# Exportar los archivos CSV
validos_df.to_csv("pedidos_curated.csv", index=False)
rechazados_df.to_csv("pedidos_rejects.csv", index=False)

In [66]:
# Instalar las dependencias
!pip install sqlalchemy psycopg2-binary

# Importar las bibliotecas
from sqlalchemy import create_engine
import pandas as pd

# URL de la base de datos PostgreSQL
database_url = "postgresql://etl_user:zISc0BFvmmfQ1u43SmeRq5XohVMo55Mn@dpg-d6qu5rh5pdvs73bhfph0-a.oregon-postgres.render.com/etl_seguros_1rr3"

# Crear la conexión con la base de datos
engine = create_engine(database_url)

# Realizar una prueba para verificar la conexión
test = pd.read_sql("SELECT 1", engine)

# Imprimir el resultado para confirmar la conexión
print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [67]:
# Cargar los datos en las tablas de PostgreSQL utilizando el engine
validos_df.to_sql(
    'pedidos_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados_df.to_sql(
    'pedidos_rejects',
    engine,
    if_exists='append',
    index=False
)

12

In [68]:
# Validar la carga de datos desde la base de datos PostgreSQL
validacion_validos = pd.read_sql(
    "SELECT * FROM pedidos_curated LIMIT 10",
    engine
)

# Mostrar los primeros registros
print(validacion_validos)

  id_pedido id_cliente fecha_pedido    monto       estado
0   PED7000     CL1138   2024-11-28  1984.03     Enviado
1   PED7002     CL1067   2024-07-13   433.46    Cancelado
2   PED7003     CL1097   2025-05-02   352.01    Cancelado
3   PED7004     CL1068   2024-12-20  1182.84      Enviado
4   PED7005     CL1030   2024-04-02  2154.60  Preparacion
5   PED7006     CL1091   2025-03-05  1921.17      Enviado
6   PED7007     CL1086   2024-10-21  1402.07  Preparacion
7   PED7008     CL1002   2024-08-04   404.61  Preparacion
8   PED7009     CL1084   2024-03-30   987.29    Pendiente
9   PED7010     CL1059   2024-06-16  1802.57   Cancelado