https://github.com/MauricioGomez-2520612022/etl-data-pipeline-2520612022-

In [56]:
import pandas as pd

In [57]:
url = "https://raw.githubusercontent.com/MauricioGomez-2520612022/etl-data-pipeline-2520612022-/refs/heads/main/data/RAW/F_envios.csv"

In [58]:
f_envios_df = pd.read_csv(url)

f_envios_df.head()

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,ENV8000,PED7100,"Boulevard Constitución, San Salvador",2024-06-02,en ruta
1,ENV8001,PED7222,"Calle El Mirador, La Libertad",2024-05-07,entregado
2,ENV8002,PED7191,"Calle El Mirador, Sonsonate",2024-05-30,devuelto
3,ENV8003,PED7186,"Av. Roosevelt, San Miguel",2024-07-03,en ruta
4,ENV8004,PED7043,"Calle Principal, San Salvador",2024-01-09,preparando

In [59]:
# Limpiar y normalizar los nombres de las columnas
f_envios_df.columns = f_envios_df.columns.str.strip().str.lower()

In [60]:
# Convertir la columna 'fecha_envio' a formato datetime
f_envios_df['fecha_envio'] = pd.to_datetime(f_envios_df['fecha_envio'], errors='coerce')

In [61]:
f_envios_df['estado_envio'] = f_envios_df['estado_envio'].str.title()

In [62]:
# Rellenar valores nulos en la columna 'estado_envio' con el valor 'desconocido'
f_envios_df['estado_envio'] = f_envios_df['estado_envio'].fillna('desconocido')

In [63]:
f_envios_df['id_envio'] = f_envios_df['id_envio'].str.strip()
f_envios_df['id_pedido'] = f_envios_df['id_pedido'].str.strip()

In [64]:
# Verificar los valores únicos de la columna 'estado_envio'
print(f_envios_df['estado_envio'].unique())

['En Ruta' 'Entregado' 'Devuelto' 'Preparando' ' Devuelto ' 'En Ruta '
 ' Entregado ' 'Entregado ' ' En Ruta ']

In [65]:
# Verificar los primeros registros después de las transformaciones
f_envios_df.head()

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,ENV8000,PED7100,"Boulevard Constitución, San Salvador",2024-06-02,En Ruta
1,ENV8001,PED7222,"Calle El Mirador, La Libertad",2024-05-07,Entregado
2,ENV8002,PED7191,"Calle El Mirador, Sonsonate",2024-05-30,Devuelto
3,ENV8003,PED7186,"Av. Roosevelt, San Miguel",2024-07-03,En Ruta
4,ENV8004,PED7043,"Calle Principal, San Salvador",2024-01-09,Preparando

In [66]:
# Separar los datos válidos (id_envio, id_pedido y fecha_envio no nulos)
validos_df = f_envios_df[
    f_envios_df['id_envio'].notna() &
    f_envios_df['id_pedido'].notna() &
    f_envios_df['fecha_envio'].notna()
].copy()

# Separar los datos rechazados (id_envio, id_pedido o fecha_envio nulos)
rechazados_df = f_envios_df[
    f_envios_df['id_envio'].isna() |
    f_envios_df['id_pedido'].isna() |
    f_envios_df['fecha_envio'].isna()
].copy()

# Ver los registros válidos y rechazados
print(validos_df.head())
print(rechazados_df.head())

  id_envio id_pedido                             direccion fecha_envio  \
0  ENV8000   PED7100  Boulevard Constitución, San Salvador  2024-06-02
1  ENV8001   PED7222        Calle El Mirador, La Libertad   2024-05-07
2  ENV8002   PED7191           Calle El Mirador, Sonsonate  2024-05-30
3  ENV8003   PED7186             Av. Roosevelt, San Miguel  2024-07-03
4  ENV8004   PED7043         Calle Principal, San Salvador  2024-01-09

  estado_envio
0      En Ruta
1    Entregado
2     Devuelto
3      En Ruta
4   Preparando
   id_envio id_pedido                          direccion fecha_envio  \
17  ENV8017   PED7073        Calle El Mirador, Santa Ana         NaT
45  ENV8045   PED7205            Col. Escalón, Sonsonate         NaT
55  ENV8055   PED7173         Pje. Las Flores, Sonsonate         NaT
56  ENV8056       NaN  Boulevard Constitución, Sonsonate  2024-12-22
58  ENV8058   PED7183      Pje. Las Flores, San Salvador         NaT

   estado_envio
17      En Ruta
45    Entregado
55    Entregado
56     Devuelto
58      En Ruta

In [67]:
# Definir la función para determinar el motivo de rechazo
def motivo(row):
    motivos = []

    if pd.isna(row['id_envio']):
        motivos.append("id_envio_vacio")

    if pd.isna(row['id_pedido']):
        motivos.append("id_pedido_vacio")

    if pd.isna(row['fecha_envio']):
        motivos.append("fecha_envio_vacia")

    return ",".join(motivos)

# Aplicar la función para obtener los motivos de rechazo
rechazados_df["motivo_rechazo"] = rechazados_df.apply(motivo, axis=1)

# Verificar los registros rechazados con la nueva columna 'motivo_rechazo'
print(rechazados_df.head())

   id_envio id_pedido                          direccion fecha_envio  \
17  ENV8017   PED7073        Calle El Mirador, Santa Ana         NaT
45  ENV8045   PED7205            Col. Escalón, Sonsonate         NaT
55  ENV8055   PED7173         Pje. Las Flores, Sonsonate         NaT
56  ENV8056       NaN  Boulevard Constitución, Sonsonate  2024-12-22
58  ENV8058   PED7183      Pje. Las Flores, San Salvador         NaT

   estado_envio     motivo_rechazo
17      En Ruta  fecha_envio_vacia
45    Entregado  fecha_envio_vacia
55    Entregado  fecha_envio_vacia
56     Devuelto    id_pedido_vacio
58      En Ruta  fecha_envio_vacia

In [68]:
# Exportar los archivos CSV
validos_df.to_csv("envios_curated.csv", index=False)
rechazados_df.to_csv("envios_rejects.csv", index=False)

In [69]:
# Instalar las dependencias
!pip install sqlalchemy psycopg2-binary

# Importar las bibliotecas
from sqlalchemy import create_engine
import pandas as pd

# URL de la base de datos PostgreSQL
database_url = "postgresql://etl_user:zISc0BFvmmfQ1u43SmeRq5XohVMo55Mn@dpg-d6qu5rh5pdvs73bhfph0-a.oregon-postgres.render.com/etl_seguros_1rr3"

# Crear la conexión con la base de datos
engine = create_engine(database_url)

# Realizar una prueba para verificar la conexión
test = pd.read_sql("SELECT 1", engine)

# Imprimir el resultado para confirmar la conexión
print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [70]:
# Cargar los datos en las tablas de PostgreSQL utilizando el engine
validos_df.to_sql(
    'envios_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados_df.to_sql(
    'envios_rejects',
    engine,
    if_exists='append',
    index=False
)

27

In [71]:
# Validar la carga de datos desde la base de datos PostgreSQL
validacion_validos = pd.read_sql(
    "SELECT * FROM envios_curated LIMIT 10",  # Seleccionar los primeros 10 registros
    engine
)

# Mostrar los primeros registros
print(validacion_validos)

  id_envio id_pedido                             direccion fecha_envio  \
0  ENV8000   PED7100  Boulevard Constitución, San Salvador  2024-06-02
1  ENV8001   PED7222        Calle El Mirador, La Libertad   2024-05-07
2  ENV8002   PED7191           Calle El Mirador, Sonsonate  2024-05-30
3  ENV8003   PED7186             Av. Roosevelt, San Miguel  2024-07-03
4  ENV8004   PED7043         Calle Principal, San Salvador  2024-01-09
5  ENV8005   PED7008            Pje. Las Flores, Sonsonate  2024-03-03
6  ENV8006   PED7169           Av. Roosevelt, San Salvador  2024-04-04
7  ENV8007   PED7153             Calle Principal, Usulután  2024-09-07
8  ENV8008   PED7207         Calle Principal, San Salvador  2025-04-23
9  ENV8009   PED7103     Boulevard Constitución, Santa Ana  2025-05-07

  estado_envio
0      En Ruta
1    Entregado
2     Devuelto
3      En Ruta
4   Preparando
5     Devuelto
6     Devuelto
7     Devuelto
8      En Ruta
9    Entregado